name: Claude Documentation Review

on:
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - '**.mdx'
  
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run on PRs or when someone comments @claude
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude'))
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Prepare prompt
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Review this Docusaurus documentation PR for configuration and build issues." > /tmp/prompt.txt
          else
            # Extract comment after @claude
            echo "${{ github.event.comment.body }}" | sed 's/@claude//' > /tmp/prompt.txt
          fi
      
      - name: Run Claude Review
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: /tmp/prompt.txt
          system_prompt: |
            You are reviewing a Docusaurus documentation site.
            Focus on: docusaurus.config.js, sidebar files, build configuration.
            Provide specific, actionable feedback.
          model: "claude-opus-4-20250514"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Allow all tools - Claude will have full capabilities
          # This includes file operations, searching, editing, etc.
          allowed_tools: ""
          max_turns: "150"
          timeout_minutes: "30"
